# Generated by Django 3.2.16 on 2025-01-03 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shiny_dex', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usershiny',
            options={'ordering': ['pokemon__dex_no']},
        ),
    ]
