# Generated by Django 3.2.16 on 2022-11-05 12:56

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiny_dex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='gen',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=50, unique=True), max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='user_shiny',
            name='slug',
            field=models.SlugField(default='<django.db.models.fields.related.ForeignKey><django.db.models.fields.related.ForeignKey>', max_length=100, unique=True),
        ),
    ]
