# Generated by Django 3.2.16 on 2023-02-26 12:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shiny_dex', '0004_user_shiny_nick_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='shinydex/'),
        ),
    ]
