# Generated by Django 3.2.16 on 2023-02-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiny_dex', '0005_alter_pokemon_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='featured_image',
            field=models.ImageField(default='placeholder', upload_to='shinydex/'),
        ),
    ]
