# Generated by Django 3.2.16 on 2023-02-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiny_dex', '0006_alter_pokemon_featured_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon',
            options={'ordering': ['dex_no']},
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type_2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
