# Generated by Django 3.2.16 on 2023-05-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiny_dex', '0007_auto_20230226_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='dex_no',
            field=models.IntegerField(),
        ),
    ]
